server:
  port: 8080

spring: 
  datasource:
    url: jdbc:mysql://database.tony.com:3306/public-lesson?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: tony
    password: tony
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    # 主Redis
    main: 
      hostName: 127.0.0.1
      port: 6379
    # 备份Redis
    bak: 
      hostName: 127.0.0.1
      port: 6380
  mvc: 
    static-path-pattern: /resources/**